# Configure this Discovery Server
eureka:
  instance:
#   hostname: 172.22.52.23
    hostname: localhost
  client: #Not a client
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
        defaultZone: http://localhost:10007/eureka/
  server:
    enableSelfPreservation: false

# HTTP (Tomcat) port
server:
  port: 10007