spring:
  application:
    name: gateway-server

#Zuul routes. Here for /student path, we are routing to localhost:8090 with extra path after that.
zuul:
  prefix: /asnbk
  routes:
    account: 
      path: /account/**
      serviceId: accountsearch-microservice
    ecl: 
      path: /ecl/**
      serviceId: eclcal-microservice      
    instrument: 
      path: /instrument/**
      serviceId: instrumentsearch-microservice
    organization: 
      path: /organization/**
      serviceId: oragnization-microservice
    regulation: 
      path: /regulation/**
      serviceId: regulation-microservice
    riskprofile: 
      path: /riskprofile/**
      serviceId: riskprofile-microservice                  
# Disable Spring Boot's "Whitelabel" default error page, so we can use our own
error:
  whitelabel:
    enabled:  false
# HTTP Server (Tomcat) Port
server: 
  port: 10006
  
  
  
eureka:
 client:
   serviceUrl:
        defaultZone: http://${DISCOVERYSERVER_PORT_10007_TCP_ADDR}:${DISCOVERYSERVER_PORT_10007_TCP_PORT}/eureka/
#       defaultZone: http://localhost:10007/eureka/
   registerWithEureka: false
   
hystrix:
 command:
   default:
     execution:
      timeout:
        enabled: false
        
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000
  OkToRetryOnAllOperations: true
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 0